apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-watcher-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher-cluster-binding
subjects:
  - kind: ServiceAccount
    name: watcher
    namespace: default # Same namespace as the ServiceAccount
roleRef:
  kind: ClusterRole
  name: pod-watcher-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher
      containers:
        - name: watcher
          image: shubhindia/watcher:master
          command: ["/watcher"]
          args: ["-config", "/config/config.yaml"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: watcher-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: watcher-config
data:
  config.yaml: |-
    namespace: default
    newest:
      - Kind: StatefulSet
        Name: web
